export type SingleMedia = {
  result: Result[]
}

export type Result = {
  tableid: number
  titleSiteArea: string
  id: number | string 
  enable: boolean 
  enddate: string 
  statusplaylist: string 
  widththumb: number
  statusgender: string 
  taghighlight: string 
  descriptionsitearea: string
  thumbnail: string
  startdateplaylist: string 
  startdate: string
  opcional9: string
  opcional15: string 
  gendersite: string 
  titleplaylist: string 
  opcional1: string 
  opcional18: string 
  statussite: string
  opcional: string
  statussitearea: string
  opcional4: string
  opcional14: string 
  title: string
  shortdescription: string
  opcional8: string
  enddateplaylist: string 
  opcional10: ''
  searchenddateplaylist: string
  idsitearea: number
  titlesite: string
  opcional5: string
  opcional7: string
  searchenddate: string
  descriptionplaylist: string
  createdAt: string 
  publishdatestring: string 
  statusmedia: string
  total: number 
  opcional2: string 
  description: string
  opcional6: string
  image2: string
  opcional3: string 
  opcional17: string
  opcional11: string
  descriptionsite: string
  ordem: number
  updatedAt: string 
  opcional19: string
  opcional12: string
  mediaType: string 
  author: string 
  idplaylist: number 
  searchstartdateplaylist: string 
  opcional16: string
  image: string 
  searchstartdate: string 
  idsite: number
  idgendersite: number 
  heightthumb: number 
  opcional13: string
  opcional20: string 
  keywords: string 
  linkSite: string
}